In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/house-pricing/sample_submission.csv
/kaggle/input/house-pricing/data_description.txt
/kaggle/input/house-pricing/train.csv
/kaggle/input/house-pricing/test.csv

In [2]:
# if you use Kaggle notebook, upload a dataset using "Add input" on the right

# Check the list of your datasets
# Option 1
from subprocess import check_output
print(check_output(["ls", "../input"]).decode("utf8"))

# Option 2 
import os
print(os.listdir("../input"))

house-pricing

['house-pricing']

## Exploratory Data Analysis

I used this book for theoretical part: 
https://www.oreilly.com/library/view/advancing-into-analytics/9781492094333/

I used this notebook as an example: 
https://www.kaggle.com/code/kashnitsky/topic-1-exploratory-data-analysis-with-pandas

## Variables: 
* categorical
    * binary (usually two levels: yes or no)
    * nominal (more than two levels)
    * ordinal
* quantitative:
    * continious
    * descrete

Categorical variables = qualitative. 
* "Which kind?"
* often represented by nonnumeric values
* example: country of origin

In [3]:
df = pd.read_csv("../input/house-pricing/test.csv")

df.shape

(1459, 80)

In [4]:
# Classify varibles

df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
count,1459.000000,1459.000000,1232.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1444.000000,1458.000000,...,1458.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000
mean,2190.000000,57.378341,68.580357,9819.161069,6.078821,5.553804,1971.357779,1983.662783,100.709141,439.203704,...,472.768861,93.174777,48.313914,24.243317,1.794380,17.064428,1.744345,58.167923,6.104181,2007.769705
std,421.321334,42.746880,22.376841,4955.517327,1.436812,1.113740,30.390071,21.130467,177.625900,455.268042,...,217.048611,127.744882,68.883364,67.227765,20.207842,56.609763,30.491646,630.806978,2.722432,1.301740
min,1461.000000,20.000000,21.000000,1470.000000,1.000000,1.000000,1879.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000
25%,1825.500000,20.000000,58.000000,7391.000000,5.000000,5.000000,1953.000000,1963.000000,0.000000,0.000000,...,318.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000
50%,2190.000000,50.000000,67.000000,9399.000000,6.000000,5.000000,1973.000000,1992.000000,0.000000,350.500000,...,480.000000,0.000000,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000
75%,2554.500000,70.000000,80.000000,11517.500000,7.000000,6.000000,2001.000000,2004.000000,164.000000,753.500000,...,576.000000,168.000000,72.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000
max,2919.000000,190.000000,200.000000,56600.000000,10.000000,9.000000,2010.000000,2010.000000,1290.000000,4010.000000,...,1488.000000,1424.000000,742.000000,1012.000000,360.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000

In [5]:
df.describe(include=["object", "bool"])

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
count,1455,1459,107,1459,1459,1457,1459,1459,1459,1459,...,1383,1381,1381,1381,1459,3,290,51,1458,1459
unique,5,2,2,4,4,1,5,3,25,9,...,6,3,4,5,3,2,4,3,9,6
top,RL,Pave,Grvl,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,...,Attchd,Unf,TA,TA,Y,Ex,MnPrv,Shed,WD,Normal
freq,1114,1453,70,934,1311,1457,1081,1396,218,1251,...,853,625,1293,1328,1301,2,172,46,1258,1204

In [6]:
df.loc[1]

Id                 1462
MSSubClass           20
MSZoning             RL
LotFrontage        81.0
LotArea           14267
                  ...
MiscVal           12500
MoSold                6
YrSold             2010
SaleType             WD
SaleCondition    Normal
Name: 1, Length: 80, dtype: object

Since our dataset is large and it's convenient to see all values of the row and the column, I apply the following settings:

In [7]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [8]:
df.loc[1]

Id                  1462
MSSubClass            20
MSZoning              RL
LotFrontage         81.0
LotArea            14267
Street              Pave
Alley                NaN
LotShape             IR1
LandContour          Lvl
Utilities         AllPub
LotConfig         Corner
LandSlope            Gtl
Neighborhood       NAmes
Condition1          Norm
Condition2          Norm
BldgType            1Fam
HouseStyle        1Story
OverallQual            6
OverallCond            6
YearBuilt           1958
YearRemodAdd        1958
RoofStyle            Hip
RoofMatl         CompShg
Exterior1st      Wd Sdng
Exterior2nd      Wd Sdng
MasVnrType       BrkFace
MasVnrArea         108.0
ExterQual             TA
ExterCond             TA
Foundation        CBlock
BsmtQual              TA
BsmtCond              TA
BsmtExposure          No
BsmtFinType1         ALQ
BsmtFinSF1         923.0
BsmtFinType2         Unf
BsmtFinSF2           0.0
BsmtUnfSF          406.0
TotalBsmtSF       1329.0
Heating             GasA
HeatingQC             TA
CentralAir             Y
Electrical         SBrkr
1stFlrSF            1329
2ndFlrSF               0
LowQualFinSF           0
GrLivArea           1329
BsmtFullBath         0.0
BsmtHalfBath         0.0
FullBath               1
HalfBath               1
BedroomAbvGr           3
KitchenAbvGr           1
KitchenQual           Gd
TotRmsAbvGrd           6
Functional           Typ
Fireplaces             0
FireplaceQu          NaN
GarageType        Attchd
GarageYrBlt       1958.0
GarageFinish         Unf
GarageCars           1.0
GarageArea         312.0
GarageQual            TA
GarageCond            TA
PavedDrive             Y
WoodDeckSF           393
OpenPorchSF           36
EnclosedPorch          0
3SsnPorch              0
ScreenPorch            0
PoolArea               0
PoolQC               NaN
Fence                NaN
MiscFeature         Gar2
MiscVal            12500
MoSold                 6
YrSold              2010
SaleType              WD
SaleCondition     Normal
Name: 1, dtype: object

# Data cleaning and preparation

### Managing Missing Values

For numeric data, pandas uses the floating-point value NaN (Not a number) to represent missing data. This is also called **a sentinel value **.

NAN handling methods in pandas: 

* dropna
* fillna
* isnull
* notnull

Two strategies of handling missing data: 
- filter out (remove)
- fill in

First, let's check how many values in every column

In [9]:
missing_values = df.isnull().sum()
missing_values

Id                  0
MSSubClass          0
MSZoning            4
LotFrontage       227
LotArea             0
Street              0
Alley            1352
LotShape            0
LandContour         0
Utilities           2
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         1
Exterior2nd         1
MasVnrType        894
MasVnrArea         15
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           44
BsmtCond           45
BsmtExposure       44
BsmtFinType1       42
BsmtFinSF1          1
BsmtFinType2       42
BsmtFinSF2          1
BsmtUnfSF           1
TotalBsmtSF         1
Heating             0
HeatingQC           0
CentralAir          0
Electrical          0
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        2
BsmtHalfBath        2
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         1
TotRmsAbvGrd        0
Functional          2
Fireplaces          0
FireplaceQu       730
GarageType         76
GarageYrBlt        78
GarageFinish       78
GarageCars          1
GarageArea          1
GarageQual         78
GarageCond         78
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1456
Fence            1169
MiscFeature      1408
MiscVal             0
MoSold              0
YrSold              0
SaleType            1
SaleCondition       0
dtype: int64

## Data Transformation

### Check duplicates

In [10]:
# check duplicates
# df.duplicated()
# show only duplicated values
duplicates = df.duplicated()
filtered = duplicates[duplicates == True]
filtered
# remove duplicates
# df.drop_duplicates()

# more advanced
# get all duplicated IDs
# ids = df["Id"]
# df[ids.isin(ids[ids.duplicated()])].sort_values("Id")

Series([], dtype: bool)

### Replace values